"""Semantic metric and cohort dimension catalog."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal

DimensionName = Literal[
    "region",
    "device",
    "channel",
    "customer_type",
    "app_version",
    "issuer",
    "payment_method",
    "processor",
    "customer_segment",
    "loyalty_tier",
    "product_category",
    "seller_id",
    "warehouse_id",
    "pipeline_name",
    "service",
    "deployment_scope",
]

Calculation = Literal[
    "count",
    "sum",
    "distinct_count",
    "ratio",
    "ratio_of_sums",
    "mean",
    "quantile",
]

MetricType = Literal["count", "currency", "ratio", "duration", "units", "score"]

ANALYTIC_DIMENSIONS: tuple[DimensionName, ...] = (
    "region",
    "device",
    "channel",
    "customer_type",
    "app_version",
    "issuer",
    "payment_method",
    "processor",
    "customer_segment",
    "loyalty_tier",
    "product_category",
    "seller_id",
    "warehouse_id",
    "pipeline_name",
    "service",
    "deployment_scope",
)

_CHECKOUT_DIMS: tuple[DimensionName, ...] = (
    "region",
    "device",
    "channel",
    "customer_type",
    "app_version",
    "customer_segment",
    "loyalty_tier",
    "product_category",
    "seller_id",
    "warehouse_id",
)
_PAYMENT_DIMS: tuple[DimensionName, ...] = (
    *_CHECKOUT_DIMS,
    "issuer",
    "payment_method",
    "processor",
)
_ORDER_DIMS = _CHECKOUT_DIMS
_ITEM_DIMS = _CHECKOUT_DIMS
_INVENTORY_DIMS: tuple[DimensionName, ...] = (
    "region",
    "product_category",
    "seller_id",
    "warehouse_id",
)
_FULFILMENT_DIMS: tuple[DimensionName, ...] = (
    "region",
    "device",
    "channel",
    "customer_type",
    "app_version",
    "customer_segment",
    "loyalty_tier",
    "warehouse_id",
)
_RETURN_DIMS: tuple[DimensionName, ...] = (
    "region",
    "device",
    "channel",
    "customer_type",
    "app_version",
    "customer_segment",
    "loyalty_tier",
    "product_category",
    "seller_id",
    "warehouse_id",
)
_FEED_DIMS: tuple[DimensionName, ...] = ("region", "product_category", "seller_id")
_PIPELINE_DIMS: tuple[DimensionName, ...] = ("pipeline_name",)
_DEPLOYMENT_DIMS: tuple[DimensionName, ...] = ("service", "deployment_scope")


@dataclass(frozen=True)
class MetricDefinition:
    """Declarative definition for a deterministic analytical metric."""

    name: str
    display_name: str
    description: str
    domain: str
    fact: str
    timestamp_column: str
    calculation: Calculation
    metric_type: MetricType
    unit: str
    higher_is_better: bool | None
    supported_dimensions: tuple[DimensionName, ...]
    value_column: str | None = None
    numerator_column: str | None = None
    denominator_column: str | None = None
    quantile: float | None = None
    expected_min: float | None = None
    expected_max: float | None = None

    def as_dict(self) -> dict[str, object]:
        return asdict(self)


METRIC_DEFINITIONS: tuple[MetricDefinition, ...] = (
    MetricDefinition(
        "checkout_sessions",
        "Checkout sessions",
        "Checkout sessions started in the period.",
        "checkout",
        "checkout",
        "started_at",
        "count",
        "count",
        "sessions",
        None,
        _CHECKOUT_DIMS,
        expected_min=0.0,
    ),
    MetricDefinition(
        "unique_checkout_customers",
        "Unique checkout customers",
        "Distinct customers who started checkout.",
        "checkout",
        "checkout",
        "started_at",
        "distinct_count",
        "count",
        "customers",
        None,
        _CHECKOUT_DIMS,
        value_column="customer_id",
        expected_min=0.0,
    ),
    MetricDefinition(
        "address_submission_rate",
        "Address submission rate",
        "Share of checkout sessions that submitted an address.",
        "checkout",
        "checkout",
        "started_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _CHECKOUT_DIMS,
        numerator_column="address_submitted",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "inventory_check_rate",
        "Inventory check rate",
        "Share of checkout sessions that reached inventory validation.",
        "checkout",
        "checkout",
        "started_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _CHECKOUT_DIMS,
        numerator_column="inventory_checked",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "payment_reach_rate",
        "Payment reach rate",
        "Share of checkout sessions that reached payment.",
        "checkout",
        "checkout",
        "started_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _CHECKOUT_DIMS,
        numerator_column="payment_started",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "checkout_conversion_rate",
        "Checkout conversion rate",
        "Share of checkout sessions that produced at least one order.",
        "checkout",
        "checkout",
        "started_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _CHECKOUT_DIMS,
        numerator_column="has_order",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "payment_attempts",
        "Payment attempts",
        "Payment authorization attempts in the period.",
        "payments",
        "payments",
        "attempted_at",
        "count",
        "count",
        "attempts",
        None,
        _PAYMENT_DIMS,
        expected_min=0.0,
    ),
    MetricDefinition(
        "payment_approval_rate",
        "Payment approval rate",
        "Share of payment attempts approved.",
        "payments",
        "payments",
        "attempted_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _PAYMENT_DIMS,
        numerator_column="approved",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "payment_decline_rate",
        "Payment decline rate",
        "Share of payment attempts declined.",
        "payments",
        "payments",
        "attempted_at",
        "ratio",
        "ratio",
        "proportion",
        False,
        _PAYMENT_DIMS,
        numerator_column="declined",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "risk_rejection_rate",
        "Risk rejection rate",
        "Share of payment attempts rejected by fraud controls.",
        "payments",
        "payments",
        "attempted_at",
        "ratio",
        "ratio",
        "proportion",
        False,
        _PAYMENT_DIMS,
        numerator_column="risk_rejected",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "payment_latency_p50_ms",
        "Payment latency p50",
        "Median payment-processor latency.",
        "payments",
        "payments",
        "attempted_at",
        "quantile",
        "duration",
        "milliseconds",
        False,
        _PAYMENT_DIMS,
        value_column="latency_ms",
        quantile=0.5,
        expected_min=0.0,
    ),
    MetricDefinition(
        "payment_latency_p95_ms",
        "Payment latency p95",
        "95th percentile payment-processor latency.",
        "payments",
        "payments",
        "attempted_at",
        "quantile",
        "duration",
        "milliseconds",
        False,
        _PAYMENT_DIMS,
        value_column="latency_ms",
        quantile=0.95,
        expected_min=0.0,
    ),
    MetricDefinition(
        "completed_orders",
        "Completed orders",
        "Orders created in the period.",
        "orders",
        "orders",
        "ordered_at",
        "count",
        "count",
        "orders",
        None,
        _ORDER_DIMS,
        expected_min=0.0,
    ),
    MetricDefinition(
        "gross_order_value",
        "Gross order value",
        "Sum of completed order totals.",
        "orders",
        "orders",
        "ordered_at",
        "sum",
        "currency",
        "currency_units",
        True,
        _ORDER_DIMS,
        value_column="total_amount",
        expected_min=0.0,
    ),
    MetricDefinition(
        "average_order_value",
        "Average order value",
        "Mean completed order total.",
        "orders",
        "orders",
        "ordered_at",
        "mean",
        "currency",
        "currency_units",
        True,
        _ORDER_DIMS,
        value_column="total_amount",
        expected_min=0.0,
    ),
    MetricDefinition(
        "average_items_per_order",
        "Average items per order",
        "Mean item count per order.",
        "orders",
        "orders",
        "ordered_at",
        "mean",
        "units",
        "items_per_order",
        None,
        _ORDER_DIMS,
        value_column="item_count",
        expected_min=1.0,
    ),
    MetricDefinition(
        "discount_share",
        "Discount share",
        "Discount amount divided by pre-discount subtotal.",
        "orders",
        "orders",
        "ordered_at",
        "ratio_of_sums",
        "ratio",
        "proportion",
        None,
        _ORDER_DIMS,
        numerator_column="discount_amount",
        denominator_column="subtotal",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "returned_order_rate",
        "Returned order rate",
        "Share of orders with at least one return request.",
        "returns",
        "orders",
        "ordered_at",
        "ratio",
        "ratio",
        "proportion",
        False,
        _ORDER_DIMS,
        numerator_column="has_return",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "units_sold",
        "Units sold",
        "Units represented by order items.",
        "orders",
        "order_items",
        "ordered_at",
        "sum",
        "units",
        "units",
        True,
        _ITEM_DIMS,
        value_column="quantity",
        expected_min=0.0,
    ),
    MetricDefinition(
        "item_revenue",
        "Item revenue",
        "Revenue represented by order-item line totals.",
        "orders",
        "order_items",
        "ordered_at",
        "sum",
        "currency",
        "currency_units",
        True,
        _ITEM_DIMS,
        value_column="line_total",
        expected_min=0.0,
    ),
    MetricDefinition(
        "inventory_exact_match_rate",
        "Inventory exact-match rate",
        "Share of snapshots where feed-reported and available quantities match.",
        "inventory",
        "inventory",
        "snapshot_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _INVENTORY_DIMS,
        numerator_column="inventory_exact_match",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "out_of_stock_rate",
        "Out-of-stock rate",
        "Share of inventory snapshots with no available units.",
        "inventory",
        "inventory",
        "snapshot_at",
        "ratio",
        "ratio",
        "proportion",
        False,
        _INVENTORY_DIMS,
        numerator_column="out_of_stock",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "low_stock_rate",
        "Low-stock rate",
        "Share of snapshots at or below the product reorder point.",
        "inventory",
        "inventory",
        "snapshot_at",
        "ratio",
        "ratio",
        "proportion",
        False,
        _INVENTORY_DIMS,
        numerator_column="low_stock",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "mean_inventory_gap_units",
        "Mean inventory gap",
        "Mean absolute difference between feed-reported and available inventory.",
        "inventory",
        "inventory",
        "snapshot_at",
        "mean",
        "units",
        "units",
        False,
        _INVENTORY_DIMS,
        value_column="inventory_gap_units",
        expected_min=0.0,
    ),
    MetricDefinition(
        "shipments",
        "Shipments",
        "Shipments created in the period.",
        "fulfilment",
        "shipments",
        "shipped_at",
        "count",
        "count",
        "shipments",
        None,
        _FULFILMENT_DIMS,
        expected_min=0.0,
    ),
    MetricDefinition(
        "on_time_delivery_rate",
        "On-time delivery rate",
        "Share of delivered shipments that arrived on or before the promise.",
        "fulfilment",
        "shipments",
        "shipped_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _FULFILMENT_DIMS,
        numerator_column="on_time",
        denominator_column="delivered",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "late_delivery_rate",
        "Late delivery rate",
        "Share of delivered shipments that arrived after the promise.",
        "fulfilment",
        "shipments",
        "shipped_at",
        "ratio",
        "ratio",
        "proportion",
        False,
        _FULFILMENT_DIMS,
        numerator_column="late_delivered",
        denominator_column="delivered",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "delivery_duration_p50_hours",
        "Delivery duration p50",
        "Median elapsed time from shipment to delivery.",
        "fulfilment",
        "shipments",
        "shipped_at",
        "quantile",
        "duration",
        "hours",
        False,
        _FULFILMENT_DIMS,
        value_column="delivery_duration_hours",
        quantile=0.5,
        expected_min=0.0,
    ),
    MetricDefinition(
        "delivery_duration_p95_hours",
        "Delivery duration p95",
        "95th percentile elapsed time from shipment to delivery.",
        "fulfilment",
        "shipments",
        "shipped_at",
        "quantile",
        "duration",
        "hours",
        False,
        _FULFILMENT_DIMS,
        value_column="delivery_duration_hours",
        quantile=0.95,
        expected_min=0.0,
    ),
    MetricDefinition(
        "scan_ingestion_lag_p95_seconds",
        "Scan ingestion lag p95",
        "95th percentile delay between source and platform receipt for warehouse scans.",
        "fulfilment",
        "scans",
        "source_event_at",
        "quantile",
        "duration",
        "seconds",
        False,
        _FULFILMENT_DIMS,
        value_column="ingestion_lag_seconds",
        quantile=0.95,
        expected_min=0.0,
    ),
    MetricDefinition(
        "return_requests",
        "Return requests",
        "Return requests created in the period.",
        "returns",
        "returns",
        "requested_at",
        "count",
        "count",
        "returns",
        None,
        _RETURN_DIMS,
        expected_min=0.0,
    ),
    MetricDefinition(
        "return_completion_rate",
        "Return completion rate",
        "Share of returns physically received.",
        "returns",
        "returns",
        "requested_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _RETURN_DIMS,
        numerator_column="return_received",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "refund_completion_rate",
        "Refund completion rate",
        "Share of returns with a completed refund.",
        "returns",
        "returns",
        "requested_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _RETURN_DIMS,
        numerator_column="refund_completed",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "refund_processing_p50_hours",
        "Refund processing p50",
        "Median elapsed time from refund initiation to completion.",
        "returns",
        "returns",
        "requested_at",
        "quantile",
        "duration",
        "hours",
        False,
        _RETURN_DIMS,
        value_column="refund_processing_hours",
        quantile=0.5,
        expected_min=0.0,
    ),
    MetricDefinition(
        "feed_success_rate",
        "Seller-feed success rate",
        "Share of seller-feed runs completed successfully.",
        "seller_feeds",
        "seller_feeds",
        "started_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _FEED_DIMS,
        numerator_column="feed_success",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "feed_rejection_rate",
        "Seller-feed record rejection rate",
        "Rejected records divided by received records.",
        "seller_feeds",
        "seller_feeds",
        "started_at",
        "ratio_of_sums",
        "ratio",
        "proportion",
        False,
        _FEED_DIMS,
        numerator_column="records_rejected",
        denominator_column="records_received",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "feed_latency_p95_seconds",
        "Seller-feed latency p95",
        "95th percentile seller-feed run latency.",
        "seller_feeds",
        "seller_feeds",
        "started_at",
        "quantile",
        "duration",
        "seconds",
        False,
        _FEED_DIMS,
        value_column="latency_seconds",
        quantile=0.95,
        expected_min=0.0,
    ),
    MetricDefinition(
        "pipeline_success_rate",
        "Pipeline success rate",
        "Share of analytical pipeline runs completed successfully.",
        "data_pipelines",
        "pipelines",
        "started_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _PIPELINE_DIMS,
        numerator_column="pipeline_success",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "pipeline_quality_pass_rate",
        "Pipeline data-quality pass rate",
        "Share of pipeline runs whose data-quality checks passed.",
        "data_pipelines",
        "pipelines",
        "started_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _PIPELINE_DIMS,
        numerator_column="data_quality_passed",
        expected_min=0.0,
        expected_max=1.0,
    ),
    MetricDefinition(
        "pipeline_row_retention_rate",
        "Pipeline row retention rate",
        "Output rows divided by input rows.",
        "data_pipelines",
        "pipelines",
        "started_at",
        "ratio_of_sums",
        "ratio",
        "proportion",
        True,
        _PIPELINE_DIMS,
        numerator_column="output_rows",
        denominator_column="input_rows",
        expected_min=0.0,
        expected_max=1.2,
    ),
    MetricDefinition(
        "pipeline_duration_p95_seconds",
        "Pipeline duration p95",
        "95th percentile pipeline run duration.",
        "data_pipelines",
        "pipelines",
        "started_at",
        "quantile",
        "duration",
        "seconds",
        False,
        _PIPELINE_DIMS,
        value_column="pipeline_duration_seconds",
        quantile=0.95,
        expected_min=0.0,
    ),
    MetricDefinition(
        "deployment_count",
        "Deployment count",
        "Service deployments recorded in the period.",
        "deployments",
        "deployments",
        "deployed_at",
        "count",
        "count",
        "deployments",
        None,
        _DEPLOYMENT_DIMS,
        expected_min=0.0,
    ),
    MetricDefinition(
        "deployment_success_rate",
        "Deployment success rate",
        "Share of deployments with successful status.",
        "deployments",
        "deployments",
        "deployed_at",
        "ratio",
        "ratio",
        "proportion",
        True,
        _DEPLOYMENT_DIMS,
        numerator_column="deployment_success",
        expected_min=0.0,
        expected_max=1.0,
    ),
)

METRIC_REGISTRY: dict[str, MetricDefinition] = {item.name: item for item in METRIC_DEFINITIONS}

if len(METRIC_REGISTRY) != len(METRIC_DEFINITIONS):  # pragma: no cover - import invariant
    raise RuntimeError("metric names must be unique")


def metric_catalog() -> list[dict[str, object]]:
    """Return a JSON-serializable metric catalog in stable order."""

    return [item.as_dict() for item in METRIC_DEFINITIONS]


def resolve_metric_names(requested: tuple[str, ...] | list[str]) -> tuple[str, ...]:
    """Resolve a requested metric list, including the all-metrics wildcard."""

    if list(requested) == ["*"]:
        return tuple(METRIC_REGISTRY)
    unknown = sorted(set(requested).difference(METRIC_REGISTRY))
    if unknown:
        raise ValueError(f"unknown metrics: {', '.join(unknown)}")
    if len(requested) != len(set(requested)):
        raise ValueError("metric names must be unique")
    return tuple(requested)
